acc/urls.py
from django.urls import path
from . import views

app_name = "acc"
urlpatterns=[
    path('index/', views.index, name="index"),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('profile/', views.profile, name="profile"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include("acc.urls")),
    path('board/', include("board.urls")),
    path('book/', include('book.urls')),
    path('trans/', include("trans.urls")),
    path('vote/', include("vote.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vote/urls.py
from django.urls import path
from . import views

app_name = "vote"

urlpatterns = [
    path('index/', views.index, name="index"),
    path('detail/<tpk>', views.detail, name="detail"),
    path('vote/<tpk>', views.vote, name="vote")
]

vote/models.py
from django.db import models
from acc.models import User

# Create your models here.
class Topic(models.Model):
    subject = models.CharField(max_length=100)
    maker = models.ForeignKey(User, on_delete=models.CASCADE, related_name="maker")
    content = models.TextField()
    voter = models.ManyToManyField(User, blank=True, related_name="voter")
    
    def __str__(self):
        return self.subject
    
class Choice(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    chname = models.CharField(max_length=100)
    chnum = models.IntegerField(default=0)
    
    def __str__(self):
        return f"{self.topic}_{self.chname}"
    
    
    
    

vote/views.py
from django.shortcuts import redirect, render
from .models import Topic, Choice
# Create your views here.
def vote(request, tpk):
    t = Topic.objects.get(id=tpk)
    if not request.user in t.voter.all():
        t.voter.add(request.user)
        cpk = request.POST.get("ch")
        c = Choice.objects.get(id=cpk)
        c.chnum += 1
        c.save()
    return redirect("vote:detail", tpk)

def detail(request, tpk):
    t = Topic.objects.get(id=tpk)
    c = t.choice_set.all()
    
    context = {
        "t":t,
        "cset":c,
    }
    return render(request, "vote/detail.html", context)

def index(request):
    t = Topic.objects.all()
    context = {
        "tset":t
    }
    return render(request, "vote/index.html", context)

templates/vote/detail.html
{% extends 'base.html' %}
{% block con %}
    
    {% load mathfilters %}

    <h1>{{ t.subject }}</h1>
    <img src="{{ t.maker.getpic }}" width="200px"><br>
    게시자 <b>{{t.maker}}</b><br>
    <textarea cols="30" rows="5" disabled>{{ t.content }}</textarea>
    <hr>

    {% if user in t.voter.all %} 
        {% for i in cset %}
            {{i.chname}} {{ i.chnum|div:t.voter.all.count|mul:100|floatformat:2 }} %<br>
        {% endfor %}
    {% else %}
        <form method="post" action="{% url 'vote:vote' t.id %}">
            {% csrf_token %}
            {% for i in cset %}
                <input type="radio" name="ch" value="{{i.id}}"> {{i.chname}} <br>
            {% endfor %}
            <button>투표하기</button>
        </form>
    {% endif %}

    

{% endblock %}

templates/vote/index.html
{% extends 'base.html' %}
{% block con %}

    <h1>투표소</h1>

    <ul>
        {% for i in tset %}
            <li><a href="{% url 'vote:detail' i.id %}">{{ i.subject }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}