acc/urls.py
from django.urls import path
from . import views

app_name = "acc"
urlpatterns=[
    path('index/', views.index, name="index"),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('profile/', views.profile, name="profile"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include("acc.urls")),
    path('board/', include("board.urls")),
    path('book/', include('book.urls')),
    path('trans/', include("trans.urls")),
    path('vote/', include("vote.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

acc/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class User(AbstractUser):
    comment = models.TextField()
    point = models.IntegerField(default=0)
    pic = models.ImageField(upload_to="user/%y")
    
    def getpic(self):
        if self.pic:
            return self.pic.url
        return "/media/익명이.png"
    

acc/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .models import User
# Create your views here.
def update(request):
    if request.method == "POST":
        u = request.user
        up = request.POST.get("upass")
        uc = request.POST.get("ucomm")
        um = request.POST.get("umail")
        pi = request.FILES.get("upic")
        if up:
            u.set_password(up)
        u.comment = uc
        u.email = um
        if pi:
            u.pic.delete()
            u.pic = pi
        u.save()
        login(request, u)
        return redirect("acc:profile")
    return render(request, "acc/update.html")

def delete(request):
    request.user.delete()
    return redirect("acc:index")

def profile(request):
    return render(request, "acc/profile.html")

def signup(request):
    if request.method == "POST":
        un = request.POST.get("uname")
        up = request.POST.get("upass")
        uc = request.POST.get("ucomm")
        pi = request.FILES.get("upic")
        User.objects.create_user(username=un, password=up, comment=uc, pic=pi)
        return redirect("acc:login")
        # print(un, up, uc, pi)
    return render(request, "acc/signup.html")


def index(request):
    return render(request, "acc/index.html")

def logout_user(request):
    logout(request)
    return redirect("acc:index")

def login_user(request):
    if request.method == "POST":
        un = request.POST.get("uname")
        up = request.POST.get("upass")
        user = authenticate(username=un, password=up)
        if user:
            login(request, user)
            return redirect("acc:index")
    return render(request, "acc/login.html")

templates/acc/index.html
{% extends 'base.html' %}


{% block con %}
    
    <h3> Welcome <b>{{ user }}</b> </h3> <br><br>

{% endblock %}

templates/acc/login.html
{% extends 'base.html' %}

{% block noauth %}
    <h1>LOGIN PAGE</h1>
    <form method="post">
        {% csrf_token %}
        USERNAME <input type="text" name="uname"><br><br>
        PASSWORD <input type="password" name="upass"><br><br>
        <button>LOGIN</button>
    </form>
{% endblock %}

templates/acc/profile.html
{% extends 'base.html' %}
{% block con %}
    <h1>{{ user }}'s PROFILE</h1>

    <img src="{{ user.getpic }}" width="200px"><br><br>

    USERNAME <input type="text" value="{{ user }}" disabled><br><br>
    EMAIL <input type="text" value="{{ user.email }}" disabled><br><br>
    POINT <input type="text" value="{{ user.point }} P" disabled><br><br>
    COMMENT <textarea disabled>{{ user.comment }}</textarea><br><br>

    <a href="{% url 'acc:update' %}"><button>계정수정</button></a>
    <a href="{% url 'acc:delete' %}"><button>계정삭제</button></a>

{% endblock %}

templates/acc/signup.html
{% extends 'base.html' %}

{% block noauth %}
    <h1>SIGNUP PAGE</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        USERNAME <input type="text" name="uname"><br><br>
        PASSWORD <input type="password" name="upass"><br><br>
        COMMENT <textarea name="ucomm"></textarea><br><br>
        <input type="file" name="upic"><br><br>
        <button>REGIST</button>
    </form>
{% endblock %}

templates/acc/update.html
{% extends 'base.html' %}
{% block con %}

    <h1>{{ user }}'s UPDATE</h1>
    
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        USERNAME <input type="text" value="{{ user }}" disabled><br><br>
        PASSWORD <input type="password" name="upass"><br><br>
        EMAIL <input type="text" value="{{ user.email }}" name="umail"><br><br>
        COMMENT <textarea name="ucomm">{{ user.comment }}</textarea><br><br>
        <input type="file" name="upic"><br><br>

        <button>업데이트</button>
    </form>
{% endblock %}