acc/urls.py
from django.urls import path
from . import views

app_name = "acc"
urlpatterns=[
    path('index/', views.index, name="index"),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('profile/', views.profile, name="profile"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update")
]

board/urls.py
from django.urls import path
from . import views

app_name = "board"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('detail/<bpk>', views.detail, name="detail"),
    path('delete/<bpk>', views.delete, name="delete"),
    path('create/', views.create, name="create"),
    path('update/<bpk>',views.update, name="update"),
    path('creply/<bpk>', views.creply, name="creply"),
    path('dreply/<bpk>/<rpk>', views.dreply, name="dreply"),
    path('likey/<bpk>', views.likey, name="likey"),
    path('cancel/<bpk>', views.cancel, name="cancel")
]

book/urls.py
from django.urls import path
from . import views

app_name = "book"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('create/', views.create, name="create")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include("acc.urls")),
    path('board/', include("board.urls")),
    path('book/', include('book.urls')),
    path('trans/', include("trans.urls")),
    path('vote/', include("vote.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trans/urls.py
from django.urls import path
from . import views

app_name = "trans"
urlpatterns =[
    path('index/', views.index, name="index")
]

vote/urls.py
from django.urls import path
from . import views

app_name = "vote"

urlpatterns = [
    path('index/', views.index, name="index"),
    path('detail/<tpk>', views.detail, name="detail"),
    path('vote/<tpk>', views.vote, name="vote")
]

templates/base.html
<div class="menus">
    <a href="{% url 'acc:index' %}">HOME</a>

    {% if user.is_authenticated %}
        <a href="{% url 'board:index' %}">BOARD</a>
        <a href="{% url 'book:index' %}">BOOK</a>
        <a href="{% url 'vote:index' %}">VOTE</a>
        <a href="{% url 'trans:index' %}">TRANS</a>
        <a href="{% url 'acc:profile' %}">PROFILE</a>
        <a href="{% url 'acc:logout' %}">LOGOUT</a>
    {% else %}
        <a href="{% url 'acc:login' %}">LOGIN</a>
        <a href="{% url 'acc:signup' %}">SIGNUP</a>
    {% endif %}
</div>


{% if user.is_authenticated %}
    {% block con %}
    <div style="text-align:center">
        <h1 style="text-align:center">이미 인증된 사용자입니다.</h1>
        <a href="{% url 'board:index' %}"><button>BOARD</button></a>
    </div>
    {% endblock %}
{% else %}
    {% block noauth %}
    <div style="text-align:center">
        <h1>로그인이 필요한 페이지입니다.</h1>
        <a href="{% url 'acc:login' %}"><button>LOGIN</button></a>
    </div>
    {% endblock %}
{% endif %}


<style>
    .menus > a{
        text-decoration: none;
        color:black;
        font-size: 20px;
        font-weight: bold;
        margin-right: 40px;
    }
    .menus > a:hover{
        color:red;
    }
    
</style>