acc/urls.py
from django.urls import path
from . import views

app_name = "acc"
urlpatterns=[
    path('index/', views.index, name="index"),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('profile/', views.profile, name="profile"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update")
]

board/urls.py
from django.urls import path
from . import views

app_name = "board"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('detail/<bpk>', views.detail, name="detail"),
    path('delete/<bpk>', views.delete, name="delete"),
    path('create/', views.create, name="create"),
    path('update/<bpk>',views.update, name="update"),
    path('creply/<bpk>', views.creply, name="creply"),
    path('dreply/<bpk>/<rpk>', views.dreply, name="dreply"),
    path('likey/<bpk>', views.likey, name="likey"),
    path('cancel/<bpk>', views.cancel, name="cancel")
]

book/urls.py
from django.urls import path
from . import views

app_name = "book"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('create/', views.create, name="create")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include("acc.urls")),
    path('board/', include("board.urls")),
    path('book/', include('book.urls')),
    path('trans/', include("trans.urls")),
    path('vote/', include("vote.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from django.db import models
from acc.models import User

# Create your models here.
class Board(models.Model):
    subject = models.CharField(max_length=200)
    writer = models.ForeignKey(User, on_delete=models.CASCADE, related_name="writer")
    content = models.TextField()
    likey = models.ManyToManyField(User, blank=True, related_name="likey")
    pubdate = models.DateTimeField()
    
    def __str__(self):
        return self.subject
    
    def summary(self):
        if len(self.content) > 10:
            return f"{self.content[:10]} ..."
        return self.content
    
class Reply(models.Model):
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    replyer = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()
    
    def __str__(self):
        return f"{self.board}_{self.replyer}"

board/views.py
from django.shortcuts import render, redirect
from .models import Board, Reply
from django.utils import timezone
from django.core.paginator import Paginator
# Create your views here.

def likey(request, bpk):
    b = Board.objects.get(id=bpk)
    b.likey.add(request.user)
    return redirect("board:detail",bpk)

def cancel(request, bpk):
    b = Board.objects.get(id=bpk)
    b.likey.remove(request.user)
    return redirect("board:detail",bpk)


def index(request):
    cate = request.GET.get("cate", "")
    kw = request.GET.get("kw", "")
    pg = request.GET.get("page", 1)
    
    if kw:
        if cate == "sub":
            b = Board.objects.filter(subject__startswith=kw)
        elif cate == "wri":
            try:
                from acc.models import User
                u = User.objects.get(username=kw)
                b = Board.objects.filter(writer=u)
            except:
                b = Board.objects.none()
        elif cate == "con":
            b = Board.objects.filter(content__contains=kw)
    else:
        b = Board.objects.all()
    
    b = b.order_by('-pubdate')
    pag = Paginator(b, 10)
    obj = pag.get_page(pg)
    context = {
        "bset" : obj,
        "kw" : kw,
        "cate" : cate
    }
    return render(request, "board/index.html", context)

def dreply(request, bpk, rpk):
    r = Reply.objects.get(id=rpk)
    if request.user == r.replyer:
        r.delete()
    return redirect("board:detail", bpk)
    

def creply(request, bpk):
    b = Board.objects.get(id=bpk)
    c = request.POST.get("com")
    if c:
        Reply(board=b, replyer=request.user, comment=c).save()
    return redirect("board:detail", bpk)


def update(request, bpk):
    b = Board.objects.get(id=bpk)
    
    if request.user != b.writer:
        # 내일 채워놓을곳!
        return redirect("board:index")
    
    if request.method == "POST":
        s = request.POST.get("sub")
        c = request.POST.get("con")
        b.subject = s
        b.content = c
        b.save()
        return redirect("board:detail", bpk)
    context = {
        "b" : b
    }
    return render(request, "board/update.html", context)


def create(request):
    if request.method == "POST":
        s = request.POST.get("sub")
        c = request.POST.get("con")
        if s and c:
            Board(subject=s, content=c, writer=request.user, pubdate=timezone.now()).save()
            return redirect("board:index")
    return render(request, "board/create.html")

def delete(request, bpk):
    b = Board.objects.get(id=bpk)
    if request.user == b.writer:
        b.delete()
    else:
        pass #내일 채워놓을곳!
    return redirect("board:index")

def detail(request, bpk):
    b = Board.objects.get(id=bpk)
    r = b.reply_set.all()
    context = {
        "b" : b,
        "rset" : r
    }
    return render(request, "board/detail.html", context)

templates/board/create.html
{% extends 'base.html' %}
{% block con %}
    <h1>게시글 생성</h1>

    <form method="post">
        {% csrf_token %}
        제목 <input type="text" name="sub"> <br><br>
        작성자 <input type="text" value="{{user}}" disabled> <br><br>
        내용 <textarea name="con" cols="50" rows="6"></textarea> <br><br>
        <button>생성</button>
    </form>
{% endblock %}

templates/board/detail.html
{% extends 'base.html' %}
{% block con %}

    <h1>{{ b.subject }}</h1>
    <textarea cols="50" rows="10" disabled>{{ b.content }}</textarea>
    <img src="{{ b.writer.getpic }}" width="200px">

    <br><br>
    <div>
        <a href="{% url 'board:index' %}"><button>홈</button></a>

        {% if user == b.writer %}
            <a href="{% url 'board:update' b.id %}"><button>수정</button></a>
            <a href="{% url 'board:delete' b.id %}"><button>삭제</button></a>
        {% endif %}
        
        {% if user in b.likey.all %}
            <a href="{% url 'board:cancel' b.id %}"><button>👎🏻</button></a>
        {% else %}
            <a href="{% url 'board:likey' b.id %}"><button>👍🏻</button></a>
        {% endif %}    
    
        <form method="post" action="{% url 'book:create' %}">
            {% csrf_token %}
            impo?<input type="checkbox" name="im">
            <button>포스팅</button>
            <input type="hidden" name="sn" value="[게시글]{{b.subject}}">
            <input type="hidden" name="su" value="{{ request.path }}">
        </form>

    
    </div>
    <br><br>
    <hr>
        <form method="post" action="{% url 'board:creply' b.id %}">
            {% csrf_token %}
            <input type="text" size="50" name="com"> 
            <button>댓글생성</button>
        </form>
    <hr>
    {% if rset %}
        {% for i in rset %}
            <img src="{{ i.replyer.getpic }}" width="100px">
            <b>{{ i.replyer }}</b> <textarea rows="5" disabled>{{ i.comment }}</textarea> 
            <a href="{% url 'board:dreply' b.id i.id %}"><button>x</button></a>  <br><br>
        {% endfor %}
    {% else %}
        <h4>첫번째 댓글을 달아주세요 😂</h4>
    {% endif %}


{% endblock %}

templates/board/index.html
{% extends 'base.html' %}
{% block con %}

    {% load mathfilters %}

    <h1>게시판</h1>

    <a href="{% url 'board:create' %}"><button>게시글작성</button></a>   <br>

    <br>

    <table border="1">
        <tr>
            <th>NO</th>
            <th>SUBJECT</th>
            <th>SUMMARY</th>
            <th>WRITER</th>
            <th>LIKEY</th>
        </tr>
        {% if bset %}
            {% for i in bset %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><a href="{% url 'board:detail' i.id %}">{{ i.subject }}</a></td>
                    <td>{{ i.summary }}</td>
                    <td>{{ i.writer }}</td>
                    <td>{{ i.likey.all.count }}</td>
                </tr>
            {% endfor %}
        {% else %}
            <tr>
                <th colspan="5">첫번째 게시글을 작성해주세요 🤣</th>
            </tr>
        {% endif %}
    
    
    </table>
    
    {% if bset.has_previous %}
        <a href="?page=1&cate={{cate}}&kw={{kw}}"><button>처음</button></a>
        <a href="?page={{bset.previous_page_number}}&cate={{cate}}&kw={{kw}}"><button>이전</button></a>
    {% else %}
        <button disabled>처음</button>
        <button disabled>이전</button>
    {% endif %}

    {% for i in bset.paginator.page_range %}
        {% if bset.number|add:2 >= i and i >= bset.number|sub:3 %}
            <a href="?page={{i}}&cate={{cate}}&kw={{kw}}"><button {% if bset.number == i %} disabled {% endif %}>{{i}}</button></a>
        {% endif %}
    {% endfor %}

    {% if bset.has_next %}
        <a href="?page={{bset.next_page_number}}&cate={{cate}}&kw={{kw}}"><button>다음</button></a>
        <a href="?page={{bset.paginator.num_pages}}&cate={{cate}}&kw={{kw}}"><button>마지막</button></a>
    {% else %}
        <button disabled>다음</button>
        <button disabled>마지막</button>
    {% endif %}

    <br><br>

    <form>
        <select name="cate">
            <option value="sub" {% if cate == 'sub' %} selected {% endif %} >제목</option>
            <option value="wri" {% if cate == 'wri' %} selected {% endif %} >작성자</option>
            <option value="con" {% if cate == 'con' %} selected {% endif %} >내용</option>
        </select>
        <input type="text" name="kw" value="{{kw}}" size="50">
        <button>검색</button>
    </form>

{% endblock %}

templates/board/update.html
{% extends 'base.html' %}
{% block con %}
    <h1>게시글 수정</h1>

    <form method="post">
        {% csrf_token %}
        제목 <input type="text" name="sub" value="{{b.subject}}"> <br><br>
        작성자 <input type="text" value="{{user}}" disabled> <br><br>
        내용 <textarea name="con" cols="50" rows="6">{{ b.content }}</textarea> <br><br>
        <button>수정</button>
    </form>
{% endblock %}